export const ListAsesors = [
    {
        'cc': 1033747211,
        'name': 'LORENA RINCON',
        'sucursal': 'Bogotá',
        'turns': '',
    },
    {
        'cc': 1022349157,
        'name': 'ALEJANDRA CUBIDES',
        'sucursal': 'Bogotá',
        'turns': '',
    },
    {
        'cc': 1014199690,
        'name': 'LEIDY RODRIGUEZ',
        'sucursal': 'Bogotá',
        'turns': '',
    },
    {
        'cc': 52188010,
        'name': 'CLAUDIA PERILLA',
        'sucursal': 'Bogotá',
        'turns': '',
    },
    {
        'cc': 52655240,
        'name': 'ANA CECILIA MORERA',
        'sucursal': 'Bogotá',
        'turns': '',
    },
    {
        'cc': 80828401,
        'name': 'OSCAR DIAZ',  
        'sucursal': 'Bogotá',
        'turns': '',
    },
    {
        'cc': 11435721,
        'name': 'FLAVIO SILVA',
        'sucursal': 'Bogotá',
        'turns': '',
    },
    {
        'cc': 1022370278,
        'name': 'VANNESA JIMENE',
        'sucursal': 'Bogotá',
        'turns': '',
    },
    {
        'cc': 1030625331,
        'name': 'PAOLA GONZALEZ',
        'sucursal': 'Bogotá',
        'turns': '',
    },
    {
        'cc': 1030661456,
        'name': 'DANIELA CUENCA',  
        'sucursal': 'Bogotá',
        'turns': '',
    },
    {
        'cc': 80239145,
        'name': 'ANDY VARGAS',  
        'sucursal': 'Bogotá',
        'turns': '',
    },
    {
        'cc': 1014227435,
        'name': 'CAMILO MORENO',
        'sucursal': 'Bogotá',
        'turns': '',
    },
    {
        'cc': 1030653936,
        'name': 'TATIANA RAMIREZ',
        'sucursal': 'Bogotá',
        'turns': '',
    },
    {
        'cc': 1032493785,
        'name': 'LISETH PRIETO',
        'sucursal': 'Bogotá',
        'turns': '',
    },
    {
        'cc': 1024476502,
        'name': 'OSCAR EDUARDO PORRAS',
        'sucursal': 'Bogotá',
        'turns': '',
    },
    {
        'cc': 1000121072,
        'name': 'BRYAN VARGAS',  
        'sucursal': 'Bogotá',
        'turns': '',
    },
    {
        'cc': 10239788254,
        'name': 'KEVIN LEÓN',
        'sucursal': 'Bogotá',
        'turns': '',
    },
    {
        'cc': 1023028357,
        'name': 'ADRIANA CRUZ',
        'sucursal': 'Bogotá',
        'turns': '',
    },
    {
        'cc': 1000148516,
        'name': 'ANDY SALGADO',
        'sucursal': 'Bogotá',
        'turns': ''
    },
    {
        'cc': 1099544827,
        'name': 'YIS MORENO',
        'sucursal': 'Tunja',
        'turns': '',
    },
    {
        'cc': 40023301,
        'name': 'BETTY PEROLLA',
        'sucursal': 'Tunja',
        'turns': '',
    },
    {
        'cc': 1049608012,
        'name': 'JENNY SALINAS',
        'sucursal': 'Tunja',
        'turns': '',
    },
]